# Generated by Django 3.2.6 on 2021-08-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('expire_date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BonusOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('off_code', models.CharField(max_length=20)),
                ('start_date', models.DateTimeField()),
                ('expire_date', models.DateTimeField()),
                ('amount', models.FloatField(blank=True, null=True)),
                ('percent', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PercentOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('expire_date', models.DateTimeField()),
                ('percent', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('books', models.ManyToManyField(related_name='percent_off', to='product.Book')),
            ],
        ),
    ]
