# Generated by Django 3.2.6 on 2021-08-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('off', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusoff',
            name='customers',
            field=models.ManyToManyField(related_name='bonus_off', to='user.Customer'),
        ),
        migrations.AddField(
            model_name='amountoff',
            name='books',
            field=models.ManyToManyField(related_name='amount_off', to='product.Book'),
        ),
    ]
