# Generated by Django 3.2.6 on 2021-09-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='final_price',
            field=models.IntegerField(default=0),
        ),
    ]
