# Generated by Django 3.2.6 on 2021-09-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_book_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='final_price',
            field=models.IntegerField(blank=True, default=models.IntegerField()),
        ),
    ]
