# Generated by Django 3.2.6 on 2021-09-03 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_book_final_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='final_price',
        ),
    ]
