# Generated by Django 3.2.5 on 2021-08-19 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateTimeField()),
                ('expire_date', models.DateTimeField()),
                ('amount', models.FloatField(blank=True, null=True)),
                ('percent', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تخفیف امتیازی',
                'verbose_name_plural': 'تخفیف های امتیازی',
            },
        ),
        migrations.CreateModel(
            name='BookDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('expire_date', models.DateTimeField()),
                ('percent', models.FloatField()),
                ('amount', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_off', to='product.book')),
            ],
            options={
                'verbose_name': 'تخفیف کتاب',
                'verbose_name_plural': 'تخفیف های کتاب',
            },
        ),
    ]
