# Generated by Django 3.2.6 on 2021-09-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
